### ISSUE TITLE
Just purchased full version, program won't open

### ISSUE THREAD

**Issue by bbusch222** [Polarrco/polarr_mac_windows_support#66]
When I attempt to open the program, a window opens, but nothing else shows up inside the window.

**Comment by skrimaging** [comment]
Assuming you are running this on a Mac...make sure you are running latest version of macOS update.. I had this issue before and updating my macOS did the trick.

see issue post https://github.com/Polarrco/polarr_mac_windows_support/issues/55

**Comment by HIGHERUP** [comment]
I'm not able to open Polarr Photo Editor. I have the Lite and wanted more effects so I purchased the version that supposed to have those from the Apple App store which states it can be used with OS X 10.10 or later. When I went to open the app I got the same window issue bbusch222 stated above. Since I have apps that won't work with Sierra I would like a refund, or I will cancel the transaction I guess rather, since the info indicates it should work with OS X 10.10.5. I recommend anyone who has the same issue puts a review at the app store
